[package]
name = "lib-bar"
version = "0.1.0-dev.0"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
